name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add PublishSPAforGitHubPages NuGet package
        run: dotnet add package PublishSPAforGitHubPages.Build --no-restore

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run Unit Tests
        run: dotnet test --no-restore --verbosity normal

      - name: Check for vulnerabilities in NuGet packages
        run: dotnet list package --vulnerable

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install WebAssembly build tools
        run: dotnet workload install wasm-tools

      - name: Add PublishSPAforGitHubPages.Build NuGet package
        run: dotnet add package PublishSPAforGitHubPages.Build --no-restore

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c:Release -p:PublishDir=publish -p:GHPages=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-files
          path: publish/wwwroot

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-files
          path: publish/wwwroot

      - name: List downloaded files
        run: ls -R published-files

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: published-files
          force_orphan: true
          cname: ${{ vars.CNAME }}